### ISSUE TITLE
Allow the copy button at formatting with '' CODE ''

### ISSUE THREAD

**Issue by beemeeup** [schplurtz/dokuwiki-plugin-copy2clipboard#11]
Hello,

Plugin works superb. I would like to have unformatted wiki text enclosed by '' CODE '' to be able to copy as well. We have several occassions where people find it to much work to always use <code> Tags instead of the above.

Thanks

**Comment by schplurtz** [comment]
Hi,
Given that this plugin uses `<code>` elements and does not parse or inspect the text of a page, what you ask can't be done. At least in this plugin.

So I'm closing this request.
