### ISSUE TITLE
Not working on local Apache but work on server

### ISSUE THREAD

**Issue by jasonwch** [schplurtz/dokuwiki-plugin-copy2clipboard#13]
Hi, I've installed this plugin from hosting  and local Apache , seems this is not working on local testing server but works on hosting side. May I know what could be the cause?

Edit:
I've tested if I put local server to HTTPS, it works. So are there anyway to correct this behaviour? Thanks

**Comment by schplurtz** [comment]
Thank you for the report.

Copy2clipboard uses the [navigator API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API#security_considerations). This API is disabled by the browser when it's not in a [secure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts). Your local installation over HTTP is not evaluated as a secure context. This is a browser decision ans copy2clipboard cannot do anything to circumvent that. And that is a good thing.

Pages served over HTTP are considered secure if they are served via the loopback interface. IE url such as `http://127.0.0.1` or `http://localhost/` are considered secure. The good news is that DokuWiki runs with PHP embedded server very well. If you have PHP (the cli version) on your local machine, you can simply start DW like this:

```
cd dokyfolder
php -S 127.0.0.1:1234 index.php
```

Then simply access DW by visiting `http://127.0.0.1:1234`.

**Comment by jasonwch** [comment]
> Thank you for the report.
> 
> Copy2clipboard uses the [navigator API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API#security_considerations). This API is disabled by the browser when it's not in a [secure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts). Your local installation over HTTP is not evaluated as a secure context. This is a browser decision ans copy2clipboard cannot do anything to circumvent that. And that is a good thing.
> 
> Pages served over HTTP are considered secure if they are served via the loopback interface. IE url such as `http://127.0.0.1` or `http://localhost/` are considered secure. The good news is that DokuWiki runs with PHP embedded server very well. If you have PHP (the cli version) on your local machine, you can simply start DW like this:
> 
> ```
> cd dokyfolder
> php -S 127.0.0.1:1234 index.php
> ```
> 
> Then simply access DW by visiting `http://127.0.0.1:1234`.

Thanks, I've added some fallback code which will work on non-HTTPS also.

something like this
`	  } else {
        // if for any reason the clipboard is unavalaible, uses the fake textarea hack to copy the content
        let textarea = document.createElement("textarea");
        textarea.value = text;
        textarea.style = "height: 1px; width : 1px";
        document.body.appendChild(textarea);
        textarea.select();
        document.execCommand("copy");
        textarea.remove();
		messageBox('cp2clipok', LANG.plugins.copy2clipboard.copied);
	  }
	  /* Add textarea hack */`

**Comment by schplurtz** [comment]
Thank you for the code. This might help others.

I won't add this code to copy2clipboard though. Mainly because it is not as safe as the navigator API.
