### ISSUE TITLE
table of content non clickable

### ISSUE THREAD

**Issue by Quentin-ctrL** [schplurtz/dokuwiki-plugin-copy2clipboard#2]
Hello,

I have some issue with this plugin and I can't click on links in toc.
Tweaking some css should fix this but unfortunatly I don't have the skills.
Moving the icon on the left could be an option ?

![image](https://user-images.githubusercontent.com/70467477/156879592-0f7de7c7-779b-4dcd-9401-b59161c6cd74.png)

Find this plugin mainly because of the geshi issue https://github.com/splitbrain/dokuwiki/issues/2614

**Comment by schplurtz** [comment]
This is the same bug as #1 . The div spans the whole width and prevent events (clics) to go to TOC.

**Comment by schplurtz** [comment]
Closing as this is a duplicate. Please refer to #1

**Comment by Quentin-ctrL** [comment]
the latest update fixed the issue
Thanks :)
