### ISSUE TITLE
report bug modify button

### ISSUE THREAD

**Issue by STYNET** [schplurtz/dokuwiki-plugin-copy2clipboard#8]
Hello,
I have a problem with your plugin.
The boutons "modify" just under a code block do not work.
Thank's ;-)

**Comment by schplurtz** [comment]
Hi,

Thanks for your report. I need a bit more data to understand what's going on, how to reproduce. Can you give a some wiki text that triggers the problem, your DW version eventually, and the template you are using ?

**Comment by schplurtz** [comment]
I've just pushed a new version with a fix. If you upgrade your plugin, the issue should disappear.

**Comment by STYNET** [comment]
Hi,
Everything is perfect !
Thank you very much for this quick fix. 
I wish you a good continuation
